### Parte 1: Análisis Exploratorio de Datos (EDA)

1. **Carga de los datos:**

   - Deberás cargar los dos conjuntos de datos que te hemos proporcionado para realizar este Laboratorio:

     - `netflix_originals.csv`

     - `netflix_titles.csv`

   Deberás revisar la estructura de cada conjunto de datos utilizando los métodos aprendidos durante la lección.

In [1]:
# Lo primero que hacemos es importar las librerias Panda y Numpy. Y hacemos que se muuestren los anchos de columna.
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None) # para poder visualizar todas las columnas de los DataFrames

### Importamos los csv.

In [2]:
datos_original = pd.read_csv("../datos/netflix_originals.csv", index_col = 0)
datos_original.head(5)

,Title,Genre,Premiere,Runtime,IMDB Score,Language
0,Enter the Anime,Documentary,"August 5, 2019",58,2.5,English/Japanese
1,Dark Forces,Thriller,"August 21, 2020",81,2.6,Spanish
2,The App,Science fiction/Drama,"December 26, 2019",79,2.6,Italian
3,The Open House,Horror thriller,"January 19, 2018",94,3.2,English
4,Kaali Khuhi,Mystery,"October 30, 2020",90,3.4,Hindi

In [3]:
datos_titulos = pd.read_csv("../datos/netflix_titles.csv", index_col = 0)
datos_titulos.head(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,NaN,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,NaN,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

### Ahora vamos a analizar los 2 data frame.

In [4]:
# Miramos la info de datos originales
visualizar_datos = datos_original.info()
visualizar_datos

<class 'pandas.core.frame.DataFrame'>
Index: 513 entries, 0 to 583
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Title       513 non-null    object
 1   Genre       513 non-null    object
 2   Premiere    513 non-null    object
 3   Runtime     513 non-null    int64
 4   IMDB Score  513 non-null    float64
 5   Language    513 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 28.1+ KB

Vemos que tenemos 6 columnas 4 de tipo str, 1 int + 1 float

In [5]:
# Miramos la info de datos titulos
visualizar_titulos = datos_titulos.info()
visualizar_titulos

<class 'pandas.core.frame.DataFrame'>
Index: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      3994 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 894.5+ KB

En este csv vemos que tenemos 12 columnas que son todas tipo str(object) menos realease year que es tipo int(numerica)

### Ahora realizamos eda numerico de los 2 dataframes.

In [6]:
datos_original.describe().T

            count       mean        std  min   25%   50%    75%    max
Runtime     513.0  94.674464  26.648121  4.0  87.0  97.0  108.0  209.0
IMDB Score  513.0   6.210916   0.968850  2.5   5.6   6.3    6.9    9.0

- Podemos tener con exactitud los datos que nos pasan de RunTime y de IMDB Score, con lo que podemos comprobar los valores.
  - En la columna Runtime podemos apreciar que hay bastante similitud entre la media y la mediana que esta en 97 y 94.6. Por lo que ese valor nos da indicios que el tiempo de las peliculas rondan los 90 minutos. 
  - En la columna IMDB Score los datos son un poco mas dispersos ya que solo tenemos ese datos de un porcentaje muy bajo de los datos generales por que solo se han votado las peliculas del dataset originales, por lo que no tenemos mucho más analisis que mostrar.

In [7]:
datos_titulos.describe().T

,count,mean,std,min,25%,50%,75%,max
release_year,8807.0,2014.180198,8.819312,1925.0,2013.0,2017.0,2019.0,2021.0

-  En esta ocasión comprobamos los datos exactos de la columna release_year donde se puede ver las estadisticas de ella.
   -  En año de lanzamiento podemos ver que la media y mediana esta también bastante proxima y con la proximidad de 25% y de 75% de los datos se puede ver que las peliculas fueron lanzadas entre 2014 y 2017.

### Ahora realizamos la misma operación pero con los datos tipo Object

In [8]:
datos_original.describe(include='object').T

         count unique                                       top freq
Title      513    513  David Attenborough: A Life on Our Planet    1
Genre      513    106                               Documentary  132
Premiere   513    350                          October 18, 2019    5
Language   513     37                                   English  352

Con el dataset original podemos apreciar que en la columna Title, tenemos las 513 peliculas unicas es un buen dato para ver que no hay duplicados, en Genre hay solo 106 datos unicos y el más repetido es Documentatty con 132 ocasiones. Con Premier son datos bastante vólatiles ya que son fecha de lanzamiento y aparecen 350 valores únicos por lo que no tiene relevancia que haya alguno repetido.Y por último la columna Language que tiene 37 valores únicos que nos dice que el data set 37 lenguajes diferentes y el más repetido es English.

In [9]:
datos_titulos.describe(include='object').T

,count,unique,top,freq
show_id,8807,8807,s8807,1
type,8807,2,Movie,6131
title,8807,8807,Zubaan,1
director,6173,4528,Rajiv Chilaka,19
cast,7982,7692,David Attenborough,19
country,7976,748,United States,2818
date_added,8797,1767,"January 1, 2020",109
rating,8803,17,TV-MA,3207
duration,3994,185,2 Seasons,425
listed_in,8807,514,"Dramas, International Movies",362
description,8807,8775,"Paranormal activity at a lush, abandoned prope...",4

Vamos a analizar los valores object del dataset titutos:
- La columna show_id nos muestra 8807 valores unicos, nos da información que no tiene valores duplicados.
- La columna Type Solo tiene 2 valores unicos que son TV Show y Movie, que separa mas peliculas de las series. Donde hay mas del 75% de valores que son pelicula.
- El la columna Title vemos que todos los valores son unicos por lo que nos da a entender que no tenemos valores duplicados.
- En la columna Director es vemos que tenemos 4528 valores únicos por lo que nos da a entender que hay muchos directores y el más repetido es Rajiv Chilaka con 19 peliculas. El resto son valores NaN y podemos cambiar el nombre a Desconocido.
- La columna cast nos muestra una gran cantidad de valores unicos y los restantes son tipo NaN por lo que podemos decidir ponerlo como desconocido.
- En la columna Country tenemos 748 datos unicos que son los diferentes paises que aparecen en la columna, y podemos ver que en más del 30% el valor más repetido osea en pais que mas peliculas tiene es USA.
- La columna Date_added nos muestra cuando se añadio la pelicula a la platarforma, por lo que podemos sacar buenas concluisiones en futuras consultas.
- La columna Rating tiene 17 columnas unicas, la más representativa con bastante diferencia es TV-Ma con 3207 de freq.
- En la columna Duration vemos que hay 185 diferentes tipos de duration de las peliculas en las que vemos que las que tiene 2 seasons son las mas repetidas.
- Listed_in tiene 514 valores unicos, que nos da ha entender que hay muchos tipos de peliculas en la columna. El valor más repetido es Dramas, Internacional Movies.
- En description vemos que casi todas las descripciones son únicas solo 4 tienen la misma repeticion y son peliculas de actividad paranormal.
  
-

### Analizamos alguna columna para ver sus valores

En este caso seleccionamos de tipo int.

In [47]:
datos_original.select_dtypes(include=['int']).T

,0,1,2,3,4,5,6,7,8,9,11,12,13,14,15,16,17,18,19,21,22,23,24,25,26,27,28,29,30,31,32,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,66,67,69,70,71,72,73,74,75,76,77,78,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,181,182,183,184,185,187,188,189,190,191,192,193,194,195,196,198,200,201,202,203,204,205,206,207,208,211,212,213,214,215,216,217,218,219,220,221,222,223,224,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,242,243,244,245,246,247,248,250,251,252,253,254,255,256,257,258,259,261,262,263,264,265,266,267,268,269,270,271,273,274,275,276,277,279,280,281,282,283,284,285,286,287,288,290,291,292,294,295,297,298,299,300,301,302,303,304,305,306,307,308,310,311,312,313,314,315,316,317,318,319,320,322,323,324,325,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,369,371,372,373,374,375,376,377,378,379,381,382,383,385,386,387,388,389,390,391,392,393,395,396,398,399,400,401,402,403,404,405,406,407,408,409,411,412,413,414,416,417,418,419,421,422,423,425,426,427,429,430,431,432,433,435,436,437,438,439,442,443,444,445,446,447,448,449,450,452,453,454,455,456,457,459,460,461,462,463,464,465,467,468,469,470,471,473,475,476,477,479,480,481,483,484,485,487,488,489,490,491,493,494,495,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,531,534,535,537,538,540,541,542,543,544,546,547,548,549,550,551,553,555,560,561,562,563,564,565,566,568,569,570,573,574,575,576,577,580,581,583
Runtime,58,81,79,94,90,147,112,149,73,139,112,97,101,90,25,144,115,102,100,97,99,120,105,89,97,107,99,95,37,89,83,85,88,86,105,95,80,4,93,100,106,97,106,103,80,101,119,80,89,94,93,96,113,86,100,102,86,104,88,97,105,90,10,106,94,112,117,70,81,103,94,98,131,87,112,102,99,116,92,83,97,112,116,102,121,95,93,92,98,85,78,101,119,101,112,96,114,97,101,56,100,94,94,21,104,63,100,126,86,142,108,102,92,83,94,92,103,89,95,103,97,125,91,90,49,98,107,118,94,103,86,83,97,99,104,102,89,98,125,89,94,94,85,34,86,91,108,95,100,90,112,124,107,92,121,90,104,92,114,98,95,78,107,92,95,96,118,105,94,52,95,100,97,89,102,131,89,93,111,75,120,96,148,94,107,104,111,83,53,95,132,98,108,106,104,90,97,113,123,115,105,101,102,122,128,82,102,80,94,104,85,84,103,95,100,89,116,118,96,114,99,87,92,90,96,93,42,92,106,151,101,90,115,92,72,139,98,92,111,98,104,88,102,30,99,129,87,117,104,111,107,97,90,101,72,83,118,113,86,108,85,102,151,98,87,120,134,85,103,94,88,37,102,100,96,113,16,119,97,81,98,95,96,107,87,101,97,103,90,125,116,99,82,97,28,93,74,60,9,100,155,55,123,103,93,119,40,120,98,104,91,95,101,105,83,91,83,86,124,94,102,118,79,134,126,98,89,58,83,136,98,114,99,130,32,104,142,92,86,95,89,117,90,117,80,87,101,19,106,111,132,97,111,124,116,112,144,76,101,92,19,102,89,101,70,96,85,39,79,73,114,121,28,95,122,107,98,108,92,97,7,96,100,103,121,114,95,83,17,131,30,112,86,100,109,28,64,94,31,48,84,70,27,45,117,104,108,121,30,47,110,92,80,49,40,96,106,97,94,78,81,91,91,95,126,31,41,112,114,125,82,98,136,107,92,39,89,124,99,101,97,129,121,140,108,11,118,121,24,100,101,105,96,47,121,100,149,64,64,114,15,79,90,132,105,97,83,110,39,40,85,26,87,97,118,23,40,80,74,90,71,98,99,40,104,149,124,85,100,94,125,84,117,136,108,12,209,130,82,120,136,112,89,85,106,97,89,109,114,51,91,153,83

Ahora lo hacemos de tipo object

In [11]:
datos_original.select_dtypes(include=['object'])

,Title,Genre,Premiere,Language
0,Enter the Anime,Documentary,"August 5, 2019",English/Japanese
1,Dark Forces,Thriller,"August 21, 2020",Spanish
2,The App,Science fiction/Drama,"December 26, 2019",Italian
3,The Open House,Horror thriller,"January 19, 2018",English
4,Kaali Khuhi,Mystery,"October 30, 2020",Hindi
...,...,...,...,...
576,Cuba and the Cameraman,Documentary,"November 24, 2017",English
577,Dancing with the Birds,Documentary,"October 23, 2019",English
580,Winter on Fire: Ukraine's Fight for Freedom,Documentary,"October 9, 2015",English/Ukranian/Russian
581,Springsteen on Broadway,One-man show,"December 16, 2018",English
583,David Attenborough: A Life on Our Planet,Documentary,"October 4, 2020",English

- En esta ocasión vemos valores de la columna Genre para identificarlos.

In [12]:
datos_original["Genre"].value_counts

<bound method IndexOpsMixin.value_counts of 0                Documentary
1                   Thriller
2      Science fiction/Drama
3            Horror thriller
4                    Mystery
               ...
576              Documentary
577              Documentary
580              Documentary
581             One-man show
583              Documentary
Name: Genre, Length: 513, dtype: object>

- Del data set titulos decido ver los valores de Listen_in

In [13]:
datos_titulos["listed_in"].value_counts

<bound method IndexOpsMixin.value_counts of 0                                           Documentaries
1         International TV Shows, TV Dramas, TV Mysteries
2       Crime TV Shows, International TV Shows, TV Act...
3                                  Docuseries, Reality TV
4       International TV Shows, Romantic TV Shows, TV ...
                              ...
8802                       Cult Movies, Dramas, Thrillers
8803               Kids' TV, Korean TV Shows, TV Comedies
8804                              Comedies, Horror Movies
8805                   Children & Family Movies, Comedies
8806       Dramas, International Movies, Music & Musicals
Name: listed_in, Length: 8807, dtype: object>

In [48]:
datos_original.sample(10)

,Title,Genre,Premiere,Runtime,IMDB Score,Language,original
24,Thunder Force,Superhero-Comedy,"April 9, 2021",105,4.4,English,original
388,Upstarts,Drama,"October 18, 2019",112,6.7,Hindi,original
148,Good Sam,Drama,"May 16, 2019",89,5.7,English,original
169,Class of '83,Drama,"August 21, 2020",98,5.8,Hindi,original
485,Ladies First,Documentary,"March 8, 2018",39,7.2,English/Hindi,original
512,Secrets of the Saqqara Tomb,Documentary,"October 28, 2020",114,7.3,English/Arabic,original
323,Altered Carbon: Resleeved,Anime/Science fiction,"March 19, 2020",74,6.5,Japanese,original
234,Sergio,Biopic,"April 17, 2020",118,6.1,English,original
73,Handsome: A Netflix Mystery Movie,Comedy,"May 5, 2017",81,5.2,English,original
204,The Prom,Musical,"December 11, 2020",132,5.9,English,original

In [49]:
datos_titulos.sample(10)

,show_id,type,Title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
5983,s5984,Movie,100 Years: One Woman's Fight for Justice,Melinda Janko,Desconocido,United States,"March 20, 2018",2016,TV-14,75 min,Documentaries,This documentary chronicles Elouise Cobell's l...
5491,s5492,Movie,Sahara,Pierre Coré,"Robert Naylor, Angela Galuppo, Daniel Brochu, ...","France, Canada","May 12, 2017",2017,TV-Y7,NaN,Children & Family Movies,When his new love is captured by an evil snake...
864,s865,Movie,Taxi No. 9211,Milan Luthria,"Nana Patekar, John Abraham, Sameera Reddy, Son...",NaN,"May 20, 2021",2006,TV-14,116 min,"Dramas, International Movies, Thrillers","When an arrogant scion hails his taxi, a cabbi..."
2285,s2286,Movie,Players,"Abbas Alibhai Burmawalla, Mastan Alibhai Burma...","Vinod Khanna, Abhishek Bachchan, Bobby Deol, S...",India,"July 5, 2020",2012,TV-14,162 min,"Action & Adventure, International Movies",Learning of a fortune in gold being secretly s...
1182,s1183,TV Show,Formula 1: Drive to Survive,Desconocido,Desconocido,United Kingdom,"March 19, 2021",2021,TV-MA,NaN,Docuseries,"Drivers, managers and team owners live life in..."
1897,s1898,Movie,Serious Men,Sudhir Mishra,"Nawazuddin Siddiqui, Nasser, Aakshath Das, Ind...",India,"October 2, 2020",2020,TV-MA,NaN,"Comedies, Dramas, International Movies",When a slum dweller spins a web of lies in pur...
1743,s1744,Movie,MOTHER,Tatsushi Omori,"Masami Nagasawa, Sadao Abe, Daiken Okudaira",Japan,"November 3, 2020",2020,TV-14,127 min,"Dramas, International Movies",Shuhei’s erratic mother feels threatened when ...
396,s397,Movie,Blood Red Sky,Peter Thorwarth,"Peri Baumeister, Alexander Scheer, Kais Setti,...",NaN,"July 23, 2021",2021,TV-MA,123 min,"Action & Adventure, Horror Movies, Internation...",When a group of terrorists hijacks an overnigh...
1117,s1118,Movie,Ibrahim a Fate to Define,Lina Al Abed,Desconocido,"Lebanon, Palestine, Denmark, Qatar","April 1, 2021",2019,TV-PG,75 min,"Documentaries, International Movies","Raised in a quiet home, Lina searches for answ..."
4479,s4480,TV Show,Great News,Desconocido,"Briga Heelan, Andrea Martin, Adam Campbell, Jo...",United States,"October 25, 2018",2017,TV-14,2 Seasons,TV Comedies,A TV news producer's ambitions take an awkward...

In [51]:
datos_original.info()

<class 'pandas.core.frame.DataFrame'>
Index: 513 entries, 0 to 583
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Title       513 non-null    object
 1   Genre       513 non-null    object
 2   Premiere    513 non-null    object
 3   Runtime     513 non-null    int64
 4   IMDB Score  513 non-null    float64
 5   Language    513 non-null    object
 6   original    513 non-null    object
dtypes: float64(1), int64(1), object(5)
memory usage: 48.2+ KB

### Miro si hay duplicados y nulos

In [17]:
# Aqui miramos si hay datos duplicados por filas
datos_duplicados_original = (datos_original.duplicated().sum())
print(datos_duplicados_original)

0

In [18]:
datos_duplicados_titulos = (datos_titulos.duplicated().sum())
datos_duplicados_titulos

np.int64(0)

In [19]:
# Vamos a ver los valores nulos de cada data frame.
datos_nulos_original = (datos_original.isnull().sum())
datos_nulos_original

Title         0
Genre         0
Premiere      0
Runtime       0
IMDB Score    0
Language      0
dtype: int64

In [20]:
datos_original.isnull().T

,0,1,2,3,4,5,6,7,8,9,11,12,13,14,15,16,17,18,19,21,22,23,24,25,26,27,28,29,30,31,32,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,66,67,69,70,71,72,73,74,75,76,77,78,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,181,182,183,184,185,187,188,189,190,191,192,193,194,195,196,198,200,201,202,203,204,205,206,207,208,211,212,213,214,215,216,217,218,219,220,221,222,223,224,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,242,243,244,245,246,247,248,250,251,252,253,254,255,256,257,258,259,261,262,263,264,265,266,267,268,269,270,271,273,274,275,276,277,279,280,281,282,283,284,285,286,287,288,290,291,292,294,295,297,298,299,300,301,302,303,304,305,306,307,308,310,311,312,313,314,315,316,317,318,319,320,322,323,324,325,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,369,371,372,373,374,375,376,377,378,379,381,382,383,385,386,387,388,389,390,391,392,393,395,396,398,399,400,401,402,403,404,405,406,407,408,409,411,412,413,414,416,417,418,419,421,422,423,425,426,427,429,430,431,432,433,435,436,437,438,439,442,443,444,445,446,447,448,449,450,452,453,454,455,456,457,459,460,461,462,463,464,465,467,468,469,470,471,473,475,476,477,479,480,481,483,484,485,487,488,489,490,491,493,494,495,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,531,534,535,537,538,540,541,542,543,544,546,547,548,549,550,551,553,555,560,561,562,563,564,565,566,568,569,570,573,574,575,576,577,580,581,583
Title,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Genre,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Premiere,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Runtime,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
IMDB Score,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

En el dataframe datos originales vemos que no tenemos datos nulos.

En el dataframe de titulos tenemos 4 columnas que tienen muchos datos nulos.

In [21]:
datos_titulos.isna().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration        4813
listed_in          0
description        0
dtype: int64

### Calculo el porcentaje de los datos nulos para ver el impacto en el dataset.

In [22]:
print((datos_titulos.isnull().sum() / len(datos_titulos)) * 100)

show_id          0.000000
type             0.000000
title            0.000000
director        29.908028
cast             9.367549
country          9.435676
date_added       0.113546
release_year     0.000000
rating           0.045418
duration        54.649710
listed_in        0.000000
description      0.000000
dtype: float64

 Decido ponerle a director y cast, los Nan como "Desconocido".

In [23]:
datos_titulos["director"].fillna('Desconocido', inplace=True)
datos_titulos["cast"].fillna('Desconocido', inplace=True)
datos_titulos.head(2)

C:\Users\User\AppData\Local\Temp\ipykernel_4620\1562111278.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  datos_titulos["director"].fillna('Desconocido', inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_4620\1562111278.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  datos_titulos["cast"].fillna('Desconocido', inplace=True)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Desconocido,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,Desconocido,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."

### Realizo la unión de los csv y lo hago con la columna title, y Title.

Antes cambio el nombre de title del data set titulos para que no me duplique las columnas

In [24]:
datos_titulos = datos_titulos.rename(columns={"title" : "Title"})

Y compruebo que todo este ok.

In [25]:
datos_titulos

,show_id,type,Title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Desconocido,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,Desconocido,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,NaN,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,Desconocido,Desconocido,NaN,"September 24, 2021",2021,TV-MA,NaN,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,Desconocido,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,Desconocido,Desconocido,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,NaN,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,NaN,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

Ahora creo la columna original para saber las series que son originales de netflix

In [26]:
datos_original["original"] = "original"

In [27]:
# Compruebo que todo esta ok
datos_original

,Title,Genre,Premiere,Runtime,IMDB Score,Language,original
0,Enter the Anime,Documentary,"August 5, 2019",58,2.5,English/Japanese,original
1,Dark Forces,Thriller,"August 21, 2020",81,2.6,Spanish,original
2,The App,Science fiction/Drama,"December 26, 2019",79,2.6,Italian,original
3,The Open House,Horror thriller,"January 19, 2018",94,3.2,English,original
4,Kaali Khuhi,Mystery,"October 30, 2020",90,3.4,Hindi,original
...,...,...,...,...,...,...,...
576,Cuba and the Cameraman,Documentary,"November 24, 2017",114,8.3,English,original
577,Dancing with the Birds,Documentary,"October 23, 2019",51,8.3,English,original
580,Winter on Fire: Ukraine's Fight for Freedom,Documentary,"October 9, 2015",91,8.4,English/Ukranian/Russian,original
581,Springsteen on Broadway,One-man show,"December 16, 2018",153,8.5,English,original
583,David Attenborough: A Life on Our Planet,Documentary,"October 4, 2020",83,9.0,English,original

### Realizo la union de las 2 data base por que ya lo tengo preparado

- Decido unirlas por Title por que es la columna que compartimos

In [28]:
datos_netflix = datos_titulos.merge(datos_original, how='left',  on = "Title")
datos_netflix

,show_id,type,Title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,Genre,Premiere,Runtime,IMDB Score,Language,original
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Desconocido,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",Documentary,"October 2, 2020",90.0,7.5,English,original
1,s2,TV Show,Blood & Water,Desconocido,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",NaN,NaN,NaN,NaN,NaN,NaN
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,NaN,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,NaN,NaN,NaN,NaN,NaN,NaN
3,s4,TV Show,Jailbirds New Orleans,Desconocido,Desconocido,NaN,"September 24, 2021",2021,TV-MA,NaN,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",NaN,NaN,NaN,NaN,NaN,NaN
4,s5,TV Show,Kota Factory,Desconocido,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a...",NaN,NaN,NaN,NaN,NaN,NaN
8803,s8804,TV Show,Zombie Dumb,Desconocido,Desconocido,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g...",NaN,NaN,NaN,NaN,NaN,NaN
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,NaN,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,NaN,NaN,NaN,NaN,NaN,NaN
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,NaN,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",NaN,NaN,NaN,NaN,NaN,NaN
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
datos_netflix.shape

(8807, 18)

### Visualizo datos netflix para comprobar que todo esta ok

In [52]:
datos_netflix.sample(10)

,show_id,type,Title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,Genre,Premiere,Runtime,IMDB Score,Language,original
485,s486,Movie,Lethal Love,Avi Federgreen,"David Pinard, Joelle Farrow, Torri Higginson, ...",NaN,"July 9, 2021",2021,TV-14,NaN,Thrillers,After a business owner starts receiving online...,NaN,NaN,NaN,NaN,NaN,NaN
2728,s2729,Movie,Humpty Sharma Ki Dulhania,Shashank Khaitan,"Varun Dhawan, Alia Bhatt, Ashutosh Rana, Sidha...",India,"April 1, 2020",2014,TV-14,131 min,"Comedies, International Movies, Romantic Movies",A small-town girl heads to Delhi to find a des...,NaN,NaN,NaN,NaN,NaN,NaN
2683,s2684,Movie,Mischief,Emcy Joseph,"Suraj Venjaramoodu, Soubin Shahir, Surabhi Lak...",India,"April 15, 2020",2019,TV-PG,120 min,"Comedies, Dramas, Independent Movies",Mistaking the sleeping passenger on his train ...,NaN,NaN,NaN,NaN,NaN,NaN
6427,s6428,Movie,Casino Royale,Martin Campbell,"Daniel Craig, Judi Dench, Eva Green, Jeffrey W...","United Kingdom, Czech Republic, United States,...","August 31, 2020",2006,PG-13,145 min,Action & Adventure,Daniel Craig makes his debut as the newly mint...,NaN,NaN,NaN,NaN,NaN,NaN
8578,s8579,Movie,Thithi,Raam Reddy,"Thammegowda S., Channegowda, Abhishek H.N., Po...","India, United States","March 9, 2017",2015,TV-MA,123 min,"Dramas, Independent Movies, International Movies","In a South Indian village, a centenarian's fun...",NaN,NaN,NaN,NaN,NaN,NaN
5500,s5501,Movie,English Babu Desi Mem,Praveen Nischol,"Shah Rukh Khan, Sonali Bendre, Rajeshwari, Sae...",India,"May 1, 2017",1996,TV-14,163 min,"Comedies, Dramas, International Movies","After his brother dies, wealthy Vikram relucta...",NaN,NaN,NaN,NaN,NaN,NaN
3857,s3858,Movie,Last Breath,"Alex Parkinson, Richard da Costa",Desconocido,"United Kingdom, Belgium, Sweden","May 6, 2019",2019,TV-MA,NaN,"Documentaries, International Movies",A commercial diver becomes trapped on the ocea...,NaN,NaN,NaN,NaN,NaN,NaN
918,s919,TV Show,Lava Ka Dhaava,Desconocido,"Jaaved Jaaferi, Rutledge Wood",India,"May 5, 2021",2021,TV-PG,NaN,Reality TV,Actor Jaaved Jaafferi brings his signature hum...,NaN,NaN,NaN,NaN,NaN,NaN
5455,s5456,Movie,Maya Memsaab,Ketan Mehta,"Deepa Sahi, Farooq Shaikh, Raj Babbar, Shah Ru...","France, United Kingdom, India","June 1, 2017",1993,TV-14,122 min,"Dramas, International Movies, Music & Musicals","A beautiful, wealthy woman’s insatiable appeti...",NaN,NaN,NaN,NaN,NaN,NaN
1982,s1983,Movie,Anaamika,Sekhar Kammula,"Nayantara, Vaibhav Reddy, Pasupathy, Harshvard...",India,"September 17, 2020",2014,TV-14,130 min,"International Movies, Thrillers",As a woman scours Hyderabad for her missing hu...,NaN,NaN,NaN,NaN,NaN,NaN

In [53]:
### Guardo el archivo ya unido
datos_netflix.to_csv("../datos/eda_netflix.csv")

### COMPROBACIONES

In [54]:
datos_netflix.sample(10)

,show_id,type,Title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,Genre,Premiere,Runtime,IMDB Score,Language,original
8187,s8188,Movie,The American President,Rob Reiner,"Michael Douglas, Annette Bening, Martin Sheen,...",United States,"January 1, 2021",1995,PG-13,113 min,"Comedies, Dramas, Romantic Movies",The widowed president strikes up a romance wit...,NaN,NaN,NaN,NaN,NaN,NaN
7207,s7208,Movie,King Jack,Felix Thompson,"Charlie Plummer, Cory Nichols, Christian Madse...",United States,"July 1, 2016",2015,NR,81 min,"Dramas, Independent Movies","Already coping with a bully, a mercurial older...",NaN,NaN,NaN,NaN,NaN,NaN
8505,s8506,Movie,The Show,Giancarlo Esposito,"Josh Duhamel, Giancarlo Esposito, Famke Jansse...",United States,"June 1, 2020",2017,TV-MA,NaN,Dramas,A disillusioned reality TV host and an idealis...,NaN,NaN,NaN,NaN,NaN,NaN
1271,s1272,TV Show,The Last Bastion,Desconocido,"Giovanni Arce, Mayella Lloclla, Rodrigo Palaci...",NaN,"February 25, 2021",2018,TV-MA,NaN,"International TV Shows, Spanish-Language TV Sh...","The Robles family, born and raised in the Amer...",NaN,NaN,NaN,NaN,NaN,NaN
6338,s6339,Movie,Blue Is the Warmest Color,Abdellatif Kechiche,"Léa Seydoux, Adèle Exarchopoulos, Salim Kechio...","France, Belgium, Spain","August 26, 2016",2013,NC-17,180 min,"Dramas, Independent Movies, International Movies","Determined to fall in love, 15-year-old Adele ...",NaN,NaN,NaN,NaN,NaN,NaN
3539,s3540,TV Show,Loo Loo Kids: Johny & Friends Musical Adventures,Desconocido,Desconocido,NaN,"September 1, 2019",2016,TV-Y,NaN,Kids' TV,Music-loving baby Johny goes on dance-filled a...,NaN,NaN,NaN,NaN,NaN,NaN
5809,s5810,Movie,XOXO,Christopher Louie,"Sarah Hyland, Graham Phillips, Chris D'Elia, H...",United States,"August 26, 2016",2016,TV-MA,NaN,"Dramas, Music & Musicals","The lives of a budding DJ, his loyal pal, a ho...",Drama,"August 26, 2016",92.0,5.3,English,original
8557,s8558,TV Show,The West Wing,Desconocido,"Martin Sheen, Rob Lowe, Allison Janney, John S...",United States,"December 25, 2015",2005,TV-14,7 Seasons,TV Dramas,This powerful political epic chronicles the tr...,NaN,NaN,NaN,NaN,NaN,NaN
914,s915,Movie,Unrest,Jennifer Brea,"Jennifer Brea, Omar Wasow, Jessica Taylor-Bearman","United Kingdom, United States","May 7, 2021",2017,TV-MA,NaN,Documentaries,"In this heart-wrenching documentary, a 28-year...",NaN,NaN,NaN,NaN,NaN,NaN
8368,s8369,TV Show,The Irish Mob,Desconocido,Mickey Spillane,NaN,"December 1, 2016",2008,TV-MA,NaN,"Crime TV Shows, Docuseries",This documentary crime series charts the rise ...,NaN,NaN,NaN,NaN,NaN,NaN

     - ¿Cuántos títulos en `netflix_titles.csv` son producciones originales de Netflix?

In [33]:
# Titulos originales Netflix
originales = datos_netflix["original"].notnull().sum()
originales

np.int64(513)

In [34]:
# Titulos no originales Netflix
no_originales = datos_netflix["original"].isnull().sum()
no_originales

np.int64(8294)

     - ¿Hay diferencias significativas en la puntuación de IMDB entre títulos originales y no originales?

No podemos evaluar dicha pregunta por que el dato IMDB solo es un dato que existe en titulos originales y no esta en titulos no originales.

### Parte 3: Uso de `loc` e `iloc`

   - Selecciona todas las filas donde el tipo de contenido sea “Movie”.

In [35]:
movies_datos_netflix = datos_netflix.loc[datos_netflix['type'] == 'Movie']
movies_datos_netflix

,show_id,type,Title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,Genre,Premiere,Runtime,IMDB Score,Language,original
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Desconocido,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",Documentary,"October 2, 2020",90.0,7.5,English,original
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,NaN,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...,NaN,NaN,NaN,NaN,NaN,NaN
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s...",NaN,NaN,NaN,NaN,NaN,NaN
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...,NaN,NaN,NaN,NaN,NaN,NaN
12,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8801,s8802,Movie,Zinzana,Majid Al Ansari,"Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...","United Arab Emirates, Jordan","March 9, 2016",2015,TV-MA,NaN,"Dramas, International Movies, Thrillers",Recovering alcoholic Talal wakes up inside a s...,NaN,NaN,NaN,NaN,NaN,NaN
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a...",NaN,NaN,NaN,NaN,NaN,NaN
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,NaN,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,NaN,NaN,NaN,NaN,NaN,NaN
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,NaN,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",NaN,NaN,NaN,NaN,NaN,NaN
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,NaN,NaN,NaN,NaN,NaN,NaN

   - Muestra solo los títulos (title) y la duración (duration) de todos los contenidos que sean de tipo “TV Show”.

In [36]:
titulo_duracion_netflix = datos_netflix.loc[datos_netflix['type'] == 'TV Show', ['Title', 'duration']]
titulo_duracion_netflix

                      Title   duration
1             Blood & Water  2 Seasons
2                 Ganglands        NaN
3     Jailbirds New Orleans        NaN
4              Kota Factory  2 Seasons
5             Midnight Mass        NaN
...                     ...        ...
8795        Yu-Gi-Oh! Arc-V  2 Seasons
8796             Yunus Emre  2 Seasons
8797              Zak Storm        NaN
8800     Zindagi Gulzar Hai        NaN
8803            Zombie Dumb  2 Seasons

[2676 rows x 2 columns]

   - Selecciona todas las filas donde el país sea “United States”.

In [37]:
filas_United_States = datos_netflix.loc[datos_netflix['country'] == 'United States']
filas_United_States

,show_id,type,Title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,Genre,Premiere,Runtime,IMDB Score,Language,original
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Desconocido,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",Documentary,"October 2, 2020",90.0,7.5,English,original
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...,NaN,NaN,NaN,NaN,NaN,NaN
15,s16,TV Show,Dear White People,Desconocido,"Logan Browning, Brandon P. Bell, DeRon Horton,...",United States,"September 22, 2021",2021,TV-MA,NaN,"TV Comedies, TV Dramas",Students of color navigate the daily slights a...,NaN,NaN,NaN,NaN,NaN,NaN
27,s28,Movie,Grown Ups,Dennis Dugan,"Adam Sandler, Kevin James, Chris Rock, David S...",United States,"September 20, 2021",2010,PG-13,NaN,Comedies,Mourning the loss of their beloved junior high...,NaN,NaN,NaN,NaN,NaN,NaN
28,s29,Movie,Dark Skies,Scott Stewart,"Keri Russell, Josh Hamilton, J.K. Simmons, Dak...",United States,"September 19, 2021",2013,PG-13,NaN,"Horror Movies, Sci-Fi & Fantasy",A family’s idyllic suburban life shatters when...,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8791,s8792,Movie,Young Adult,Jason Reitman,"Charlize Theron, Patton Oswalt, Patrick Wilson...",United States,"November 20, 2019",2011,R,NaN,"Comedies, Dramas, Independent Movies",When a divorced writer gets a letter from an o...,NaN,NaN,NaN,NaN,NaN,NaN
8793,s8794,Movie,"Yours, Mine and Ours",Raja Gosnell,"Dennis Quaid, Rene Russo, Sean Faris, Katija P...",United States,"November 20, 2019",2005,PG,NaN,"Children & Family Movies, Comedies",When a father of eight and a mother of 10 prep...,NaN,NaN,NaN,NaN,NaN,NaN
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a...",NaN,NaN,NaN,NaN,NaN,NaN
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,NaN,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,NaN,NaN,NaN,NaN,NaN,NaN
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,NaN,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",NaN,NaN,NaN,NaN,NaN,NaN

   - Muestra todas las películas (type = “Movie”) y selecciona las columnas title y director.

In [38]:
tipo_movie = datos_netflix.loc[datos_netflix['type'] == 'Movie', ['Title', 'duration']]
tipo_movie

                                 Title duration
0                 Dick Johnson Is Dead   90 min
6     My Little Pony: A New Generation      NaN
7                              Sankofa  125 min
9                         The Starling  104 min
12                        Je Suis Karl  127 min
...                                ...      ...
8801                           Zinzana      NaN
8802                            Zodiac  158 min
8804                        Zombieland      NaN
8805                              Zoom      NaN
8806                            Zubaan  111 min

[6131 rows x 2 columns]

   - Selecciona los títulos (title) y géneros (listed_in) de todas las producciones lanzadas en 2018.

In [39]:
producciones_2018 = datos_netflix.loc[datos_netflix['release_year'] == 2018, ['Title', 'listed_in']]
producciones_2018

,Title,listed_in
21,Resurrection: Ertugrul,"International TV Shows, TV Action & Adventure,..."
37,Angry Birds,"Kids' TV, TV Comedies"
73,King of Boys,"Dramas, International Movies"
94,Show Dogs,"Children & Family Movies, Comedies"
96,If I Leave Here Tomorrow: A Film About Lynyrd ...,"Documentaries, Music & Musicals"
...,...,...
8732,White Chamber,"Sci-Fi & Fantasy, Thrillers"
8743,Wildlife,"Dramas, Independent Movies"
8774,يوم الدين,"Dramas, Independent Movies, International Movies"
8775,Yeh Meri Family,"International TV Shows, TV Comedies"
8803,Zombie Dumb,"Kids' TV, Korean TV Shows, TV Comedies"

   - Selecciona las filas donde la columna director esté vacía y muestra solo los títulos (title).

In [40]:
director_desconocido = datos_netflix.loc[datos_netflix['director'] == 'Desconocido', ['Title']]
director_desconocido

                                    Title
1                           Blood & Water
3                   Jailbirds New Orleans
4                            Kota Factory
10    Vendetta: Truth, Lies and The Mafia
14        Crime Stories: India Detectives
...                                   ...
8795                      Yu-Gi-Oh! Arc-V
8796                           Yunus Emre
8797                            Zak Storm
8800                   Zindagi Gulzar Hai
8803                          Zombie Dumb

[2634 rows x 1 columns]

2. **Acceso a datos específicos con `iloc`:**

   - Selecciona las primeras 5 filas del conjunto de datos y muestra solo las columnas title, director y country.

In [41]:
cinco_filas = datos_netflix.iloc[:5,[datos_netflix.columns.get_loc('Title'), datos_netflix.columns.get_loc('director'), datos_netflix.columns.get_loc ('country')]]
cinco_filas

                   Title         director        country
0   Dick Johnson Is Dead  Kirsten Johnson  United States
1          Blood & Water      Desconocido   South Africa
2              Ganglands  Julien Leclercq            NaN
3  Jailbirds New Orleans      Desconocido            NaN
4           Kota Factory      Desconocido          India

   - Muestra las últimas 5 filas del conjunto de datos y selecciona las columnas title y description.

In [42]:
ultimas_filas = datos_netflix.iloc[-5:,[datos_netflix.columns.get_loc('Title'), datos_netflix.columns.get_loc('description')]]
ultimas_filas

            Title                                        description
8802       Zodiac  A political cartoonist, a crime reporter and a...
8803  Zombie Dumb  While living alone in a spooky town, a young g...
8804   Zombieland  Looking to survive in a world taken over by zo...
8805         Zoom  Dragged from civilian life, a former superhero...
8806       Zubaan  A scrappy but poor boy worms his way into a ty...

   - Selecciona las primeras 10 filas del dataset y muestra las columnas desde la segunda hasta la quinta (incluidas).

In [43]:
primeras_diez = datos_netflix.iloc[:10, 1:6]
primeras_diez

,type,Title,director,cast,country
0,Movie,Dick Johnson Is Dead,Kirsten Johnson,Desconocido,United States
1,TV Show,Blood & Water,Desconocido,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa
2,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN
3,TV Show,Jailbirds New Orleans,Desconocido,Desconocido,NaN
4,TV Show,Kota Factory,Desconocido,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India
5,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN
6,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN
7,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin..."
8,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom
9,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States

   - Muestra las últimas 7 filas del dataset y selecciona las columnas title, director, y country usando índices posicionales.

In [44]:
ultimas_siete = datos_netflix.iloc[-7:,[datos_netflix.columns.get_loc('Title'), datos_netflix.columns.get_loc('director'), datos_netflix.columns.get_loc('country')]]
ultimas_siete

                   Title         director                       country
8800  Zindagi Gulzar Hai      Desconocido                      Pakistan
8801             Zinzana  Majid Al Ansari  United Arab Emirates, Jordan
8802              Zodiac    David Fincher                 United States
8803         Zombie Dumb      Desconocido                           NaN
8804          Zombieland  Ruben Fleischer                 United States
8805                Zoom     Peter Hewitt                 United States
8806              Zubaan      Mozez Singh                         India

   - Selecciona las filas desde la 15 hasta la 25 (incluidas) y muestra las primeras 4 columnas.

In [45]:
filas_entre = datos_netflix.iloc[15:26, 1:5]
filas_entre

,type,Title,director,cast
15,TV Show,Dear White People,Desconocido,"Logan Browning, Brandon P. Bell, DeRon Horton,..."
16,Movie,Europe's Most Dangerous Man: Otto Skorzeny in ...,"Pedro de Echave García, Pablo Azorín Williams",Desconocido
17,TV Show,Falsa identidad,Desconocido,"Luis Ernesto Franco, Camila Sodi, Sergio Goyri..."
18,Movie,Intrusion,Adam Salky,"Freida Pinto, Logan Marshall-Green, Robert Joh..."
19,TV Show,Jaguar,Desconocido,"Blanca Suárez, Iván Marcos, Óscar Casas, Adriá..."
20,TV Show,Monsters Inside: The 24 Faces of Billy Milligan,Olivier Megaton,Desconocido
21,TV Show,Resurrection: Ertugrul,Desconocido,"Engin Altan Düzyatan, Serdar Gökhan, Hülya Dar..."
22,Movie,Avvai Shanmughi,K.S. Ravikumar,"Kamal Hassan, Meena, Gemini Ganesan, Heera Raj..."
23,Movie,Go! Go! Cory Carson: Chrissy Takes the Wheel,"Alex Woo, Stanley Moore","Maisie Benson, Paul Killam, Kerry Gudjohnsen, ..."
24,Movie,Jeans,S. Shankar,"Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi..."
25,TV Show,Love on the Spectrum,Desconocido,Brooke Satchwell

   - Muestra las filas 20 a 30 y solo las columnas title, release_year, y rating usando índices posicionales.

In [46]:
filas_datos = datos_netflix.iloc[20:31,[datos_netflix.columns.get_loc('Title'), datos_netflix.columns.get_loc('release_year'), datos_netflix.columns.get_loc('rating')]]
filas_datos

                                              Title  release_year rating
20  Monsters Inside: The 24 Faces of Billy Milligan          2021  TV-14
21                           Resurrection: Ertugrul          2018  TV-14
22                                  Avvai Shanmughi          1996  TV-PG
23     Go! Go! Cory Carson: Chrissy Takes the Wheel          2021   TV-Y
24                                            Jeans          1998  TV-14
25                             Love on the Spectrum          2021  TV-14
26                                   Minsara Kanavu          1997  TV-PG
27                                        Grown Ups          2010  PG-13
28                                       Dark Skies          2013  PG-13
29                                         Paranoia          2013  PG-13
30                                  Ankahi Kahaniya          2021  TV-14